# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name        = %q{FeedFinder}
  s.version     = "0.3.0"
  s.platform    = Gem::Platform::RUBY
  s.homepage    = %q{http://github.com/olav/FeedFinder}
  s.authors     = ["Olav Bjorkoy", "Kim Joar Bekkelund"]
  s.email       = %q{olav@bjorkoy.com}
  s.summary     = %q{Discovers feeds for a given URL.}
  s.description = %q{Discovers feeds for a given URL.}

  s.required_rubygems_version = ">= 1.3.6"

  s.add_development_dependency "rspec"

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {spec}/*`.split("\n")
  s.require_paths = ["lib"]
end
